name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: '🚀 New'
      labels:
          - '✨ Feature'
          - '💥 Breaking change'
    - title: '🧹 Enhancements'
      labels:
          - '🧹 Enhancement'
          - '⚡️ Performance'
          - '🔥 Clean up'
    - title: '🐛 Fixes'
      labels:
          - '🐛 Bug'
          - '🚑 Hotfix'
          - '🔒️ Security'
    - title: '📚 Documentation'
      labels:
          - '📝 Documentation'
    - title: '🏗️ Infrastructure'
      labels:
          - '🔧 Configuration'  
          - '🧱 Infrastructure'
    - title: 'Other changes'
      collapse-after: 10
    - title: '⬆️ Dependencies'
      collapse-after: 3
      labels: 
          - '🤖 Dependencies'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
    $CHANGES
    
    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
    
    Contributors: $CONTRIBUTORS

